#!/usr/bin/env sh
. "$(dirname "$0")/husky.sh"
# husky
# This script is executed before pushing changes to the remote repository.
# Run formatting
npm run format
if [ $? -ne 0 ]; then
  echo "Linting failed. Push aborted."
  exit 1
fi
echo "Linting passed. Proceeding with tests."
# Run linting
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Push aborted."
  exit 1
fi
echo "Linting passed. Proceeding with tests."
# Run tests
npm test
if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi
echo "Tests passed. Proceeding with push."
# Run type checking
npm run typecheck
if [ $? -ne 0 ]; then
  echo "Type checking failed. Push aborted."
  exit 1
fi
echo "Type checking passed. Proceeding with push."
